### ISSUE TITLE
convert_to_tfrecord.py KeyError

### ISSUE THREAD

**Issue by jaipadmakumar** [aqlaboratory/rgn#10]
I'm able to successfully run the `jackhmmer.sh` and `convert_to_proteinnet.py` scripts but get the following error when running `convert_to_tfrecord.py`:

```
Traceback (most recent call last):
  File "data_processing/convert_to_tfrecord.py", line 104, in <module>
    tfrecord_serialized = dict_to_tfrecord(dict_).SerializeToString()
  File "data_processing/convert_to_tfrecord.py", line 71, in dict_to_tfrecord
    id_ = _bytes_feature([dict_['id']])
KeyError: 'id'

```

Not sure what exactly my problem here is.

**Comment by jaipadmakumar** [comment]
Figured it out, the problem seemed to actually stem from `convert_to_proteinnet.py`. My FASTA file had the format where the sequence had a break every 70 characters, causing `convert_to_proteinnet.py` to not read the entire sequence. 

Resolved by just removing all breaks from the sequence.

**Comment by alquraishi** [comment]
Thanks for digging into this. To be honest I didn't test this very carefully as it was primarily used in my own internal pipeline for ProteinNet where everything is standardized. I will update the docs to point out that the sequence should not have any spaces.
