### ISSUE TITLE
How to predict if i have one sequence and the pretrained model CASP12

### ISSUE THREAD

**Issue by yy1252450987** [aqlaboratory/rgn#4]
I have a sequence like "...GCTADEGCHLPAGT...", what i need to do to predict ???

**Comment by alquraishi** [comment]
You need to generate a PSSM for the sequence before a prediction can be made. In principle it's possible to predict from a single sequence but I wouldn't recommend it. I'll add some documentation to the README soon to describe how I generate PSSMs. The full description is in the [ProteinNet paper](https://arxiv.org/abs/1902.00249) but I will post the script here.

**Comment by yy1252450987** [comment]
Actually, i have 100,000 sequences, is it possible in time-scale to generate PSSM using easel software cited in ProteinNet Paper ?

**Comment by alquraishi** [comment]
Yes absolutely although it may be a bit slow, depending on the database you're using. An alternative is to use something like HHblits, which is much faster than JackHMMer, and then convert it to the stockholm file format before feeding to Easel.

**Comment by alquraishi** [comment]
I have added scripts and a set of instructions for making a prediction out of a single sequence, including generating the PSSM using JackHMMer. They are available [here](https://github.com/aqlaboratory/rgn#predict-structure-of-a-single-new-sequence-using-a-trained-model).
