### ISSUE TITLE
Missing data for running tests

### ISSUE THREAD

**Issue by AlexeyG** [aqlaboratory/rgn#5]
Hi,

Very interested in your work, and wanted to try running your code myself - thanks for making it public!

But I am running into a bit of trouble with running the tests. `tests.py` depends on a few hardcoded data paths (e.g. `data/unofficial/...`). It's not immediately clear where these data can be obtained from/how they can be re-constructed. Some instructions/links to obtain the necessary test data would be great.

~ Alexey

**Comment by alquraishi** [comment]
Thanks for catching this! I hadn't realized the tests-associated data were missing. It's in the repo now, [here](https://github.com/aqlaboratory/rgn/blob/master/model/tests_data.zip). Just unzip in `<baseDirectory>`.
