### ISSUE TITLE
File format clarifications needed for training new models

### ISSUE THREAD

**Issue by persalteas** [aqlaboratory/rgn#7]
Hello, thank you first for the clear Readme.
Something is missing (to me) : the convert_to_tfrecord.py script takes "Mathematica protein files" as input. What are they ? I cannot find such format in [the doc](https://reference.wolfram.com/language/guide/ChemicalDataFormats.html). Is it possible to start from a dataset of MMCIF files + PSSMs ?

**Comment by alquraishi** [comment]
Sorry this was an error in the comment--it's a holdover from an older version. I corrected it now. It's just referring to the Text-based file format for ProteinNet that's described in the docs [here](https://github.com/aqlaboratory/proteinnet/blob/master/docs/proteinnet_records.md#file-formats).
