### ISSUE TITLE
data dimension error?

### ISSUE THREAD

**Issue by HadXu** [aqlaboratory/rgn#8]
why train and predict rgn with 42 dimension (EVOLUTIONARY) while text-based file is 21 dimension? and addition one dimension refer to(20+1)?  thank you!

**Comment by alquraishi** [comment]
In the pre-trained RGN models, the inputs are duplicated and concatenated once to yield 42 dimensions in total. This [script](https://github.com/aqlaboratory/rgn/blob/master/data_processing/convert_to_proteinnet.py) gives an example of how the raw PSSM / IC data is converted into a ProteinNet record. The additional dimension in 21 is information content (IC).
